CREATE DATABASE customer_project;
USE customer_project;

CREATE TABLE shopping_data (
    Age INT,
    Gender VARCHAR(20),
    Item_Purchased VARCHAR(100),
    Category VARCHAR(50),
    Purchase_Amount_USD INT,
    Location VARCHAR(100),
    Size VARCHAR(10),
    Color VARCHAR(50),
    Season VARCHAR(20),
    Review_Rating VARCHAR(20),
    Subscription_Status VARCHAR(10),
    Shipping_Type VARCHAR(50),
    Discount_Applied VARCHAR(10),
    Promo_Code_Used VARCHAR(10),
    Previous_Purchases INT,
    Payment_Method VARCHAR(50),
    Frequency_of_Purchases VARCHAR(50),
    Age_Group VARCHAR(50)
);


LOAD DATA INFILE 'C:/ProgramData/MySQL/MySQL Server 8.0/Uploads/cleaned_customer_shopping_data.csv'
INTO TABLE shopping_data
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;


-- Q1. Check Total Rows in Dataset

SELECT COUNT(*) AS Total_Rows
FROM shopping_data;


-- Q2. Preview Dataset

SELECT *
FROM shopping_data
LIMIT 10;


-- Q3. What is the Total Revenue Generated?

SELECT SUM(Purchase_Amount_USD) AS Total_Revenue
FROM shopping_data;


-- Q4. What is the Average Purchase Amount?

SELECT ROUND(AVG(Purchase_Amount_USD),2) AS Average_Purchase
FROM shopping_data;


-- Q5. What is the Revenue Generated by Male vs Female Customers?

SELECT Gender,
       SUM(Purchase_Amount_USD) AS Total_Revenue
FROM shopping_data
GROUP BY Gender;


-- Q6. Which are the Top 10 Most Purchased Products?

SELECT Item_Purchased,
       COUNT(*) AS Total_Orders
FROM shopping_data
GROUP BY Item_Purchased
ORDER BY Total_Orders DESC
LIMIT 10;


-- Q7. Which Product Categories Generate the Highest Revenue?

SELECT Category,
       SUM(Purchase_Amount_USD) AS Total_Revenue
FROM shopping_data
GROUP BY Category
ORDER BY Total_Revenue DESC;


-- Q8. Which Locations Generate the Highest Revenue?

SELECT Location,
       SUM(Purchase_Amount_USD) AS Total_Revenue
FROM shopping_data
GROUP BY Location
ORDER BY Total_Revenue DESC
LIMIT 10;


-- Q9. Which Season has the Highest Sales?

SELECT Season,
       SUM(Purchase_Amount_USD) AS Total_Sales
FROM shopping_data
GROUP BY Season
ORDER BY Total_Sales DESC;


-- Q10. Which Shipping Type is Used the Most?

SELECT Shipping_Type,
       COUNT(*) AS Total_Usage
FROM shopping_data
GROUP BY Shipping_Type
ORDER BY Total_Usage DESC;


-- Q11. Which Payment Method is Used Most Frequently?

SELECT Payment_Method,
       COUNT(*) AS Total_Transactions
FROM shopping_data
GROUP BY Payment_Method
ORDER BY Total_Transactions DESC;


-- Q12. Do Customers with Discounts Spend More?

SELECT Discount_Applied,
       ROUND(AVG(Purchase_Amount_USD),2) AS Avg_Spending
FROM shopping_data
GROUP BY Discount_Applied;


-- Q13. What is the Average Review Rating by Category?

SELECT Category,
       ROUND(AVG(Review_Rating),2) AS Avg_Rating
FROM shopping_data
GROUP BY Category
ORDER BY Avg_Rating DESC;


-- Q14. Which Customers are Repeat Buyers?

SELECT Previous_Purchases,
       COUNT(*) AS Total_Customers
FROM shopping_data
GROUP BY Previous_Purchases
ORDER BY Previous_Purchases DESC;


-- Q15. Which Age Group Spends the Most?

SELECT Age_Group,
       SUM(Purchase_Amount_USD) AS Total_Spending
FROM shopping_data
GROUP BY Age_Group
ORDER BY Total_Spending DESC;


-- Q16. Which Colors are Most Preferred by Customers?

SELECT Color,
       COUNT(*) AS Total_Orders
FROM shopping_data
GROUP BY Color
ORDER BY Total_Orders DESC;


-- Q17. Which Purchase Frequency Group Generates the Most Revenue?

SELECT Frequency_of_Purchases,
       SUM(Purchase_Amount_USD) AS Total_Revenue
FROM shopping_data
GROUP BY Frequency_of_Purchases
ORDER BY Total_Revenue DESC;